### ISSUE TITLE
Fix Touchpad sensitivity

### ISSUE THREAD

**Issue by ezeeyahoo** [RehabMan/OS-X-Voodoo-PS2-Controller#100] opened 2016-12-02 17:17 UTC
I can move cursor/pointer just by hovering and without touching the touchpad. Whenever I lift or place finger, it disturb the position every time.  How can I fix this weird issue?

**Comment by RehabMan** [comment] 2016-12-07 19:15
duplicate of issue #37.  Closing.

**Closed by RehabMan** 2016-12-07 19:15 UTC
