### ISSUE TITLE
VoodooPS2Daemon does not work on HighSierra macOS or another files.

### ISSUE THREAD

**Issue by jonathanburgossaldivia** [RehabMan/OS-X-Voodoo-PS2-Controller#127] opened 2017-07-04 23:22 UTC
It works correctly in macOS Sierra, you see the preferences panel of the Trackpad as the NATIVE, unfortunately no longer works in this version of macOS HighSierra, probably need an update one of your files, i have prepared some shell scripts in plain text for you to install all files (daemons, and others), maybe you can help me to correct something, I regret to have written you here since I do not have your mail, for thank you very much for all the support you offer for PCs, this is the link where my files are hosted for you: https://drive.google.com/file/d/0B3nXjlaODkBvLTZmV0tTX0g1d1k/view?usp=sharing  .

**Comment by RehabMan** [comment] 2017-08-10 15:04
Duplicate of #125

**Closed by RehabMan** 2017-08-10 15:04 UTC

**Comment by ykla** [comment] 2017-08-17 05:01
I have the same issue.

**Comment by bySabi** [comment] 2017-12-10 10:33
@ykla @jonathanburgossaldivia do you solved it??

sames here

**Comment by RehabMan** [comment] 2017-12-11 14:52
Use the forums.
https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/

**Comment by jonathanburgossaldivia** [comment] 2017-12-11 18:31
Is working again in macOS highsierra, works perfect now ;)

**Comment by bySabi** [comment] 2017-12-12 07:56
@jonathanburgossaldivia do you have Trackpad pref panel?

**Comment by RehabMan** [comment] 2017-12-12 15:12
This bug is already fixed.
And it has nothing to do with a Trackpad prefpane.
Use the forums.
